### ISSUE TITLE
Running CLI on Linux/MAC in the installation folder throws "unhandled" exception

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/automate#88]
# Repro

On MacOS/Linux: running this command: 

`/Users/<username>/.dotnet/tools/automate info --os` 

generates an unhandled exception in the CLI, that is reported as text in stderr, similar to this:

```
Unhandled exception. System.IO.IOException: The file '/Users/roscoe/.dotnet/tools/automate' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.DirectoryInfo.Create()
   at NReco.Logging.File.FileLoggerProvider.FileWriter.<OpenFile>g__createLogFileStream|7_0(<>c__DisplayClass7_0& )
   at NReco.Logging.File.FileLoggerProvider.FileWriter.OpenFile(Boolean append)
   at NReco.Logging.File.FileLoggerProvider.FileWriter..ctor(FileLoggerProvider fileLogPrv)
   at NReco.Logging.File.FileLoggerProvider..ctor(String fileName, FileLoggerOptions options)
   at Microsoft.Extensions.Logging.FileLoggerExtensions.<>c__DisplayClass1_0.<AddFile>b__0(IServiceProvider s
``` 

The root cause is that in Linux/macOS, you cannot have a file and a directory with the same name created in the same directory. Whereas in Windows you can.

When the CLI starts up it creates a `automate.log` file a directory called `automate` in the location where the command `automate` is executed. In the case where the `automate` command is run in the `/Users/<username>/.dotnet/tools` folder there is already a file named `automate`, so creating the directory `automate` fails, and this raises an exception that is not expected by the CLI. This is why that exception is reported back to the caller as text (not structured JSON) as is expected.

# Solution

We need to review where the *.log file should be written, whether the CLI is run in the installation directory or in a source code tree.

In the former, we need to put the file in a central well-known location like (Windows) `C:\Users\<username>\AppData\Local\automate` (MacOS/Linux) `/Users/<username>/.local/share/automate` (aka: `Environment.SpecialFolder.LocalApplicationData`)

In the later, it can be the current directory where the tool is being run.

**Comment by jezzsantos** [comment]
The parts of the CLI that this changes:
1. the "automate" folder where pattern, toolkits, drafts and localstate are saved. `automate/*.*`
2. the log file `automate/automate.log`
3. the machine state file, `automate/MachineState.json`
4. AI telemetry cache `automate/usage-cache/*.*`

If running on Linux/MacOS and any of these are written to the same directory as the executable is running from then we get a runtime error.

Consider that `automate` can be installed using `dotnet tool install automate` either globally or locally to any directory.
In the case it is installed globally (`dotnet tool install automate --global`) then it is installed into `%USERPROFILE%/.dotnet/tools`.
In the case it is installed locally (`--local`) the executable is installed elsewhere on the machine, but not in the same directory as where it was installed.

# Solution

* If we run `automate` in the same directory as `%USERPROFILE%/.dotnet/tools` (ie if CurrentDirectory == `%USERPROFILE%/.dotnet/tools`) then we need to use a different directory name (such as: `_automate`) for all local state files.
* MachineState should always be saved to `%LocalApplicationData%/automate/MachineState.json`
* AI Telemetry should always be saved to `%LocalApplicationData%/automate/usage-cache/*.*`
* Log file should always be written to `%LocalApplicationData%/automate/automate.log`
